spring:
  application:
    name: bff-agendador
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true

usuario:
  url: usuario:8080/usuario
  email: admin@admin.com
  senha: admin

agendador-tarefa:
  url: agendador-tarefas:8081/tarefas

notificacao:
  url: notificacao:8082/email

# Roda a cada 5 minutos, todos os dias.
cron:
  horario: 0 0/5 * * * ?

server:
  port: 8083